### ISSUE TITLE
krystals or crystals-rs?

### ISSUE THREAD

**Issue by faern** [kammoh/krystals#1]
Hi!

I see that both crates [`krystals`](https://crates.io/crates/krystals) and [`crystals-rs`](https://crates.io/crates/crystals-rs) were initially published by you on the same day, with the same content. However, only one of them lead to this repository. As someone looking around for a Rust implementation of CRYSTALS-Kyber I just wanted to reach out and check what the status is. Are both these crates intended to be used? If so, what's going to be the difference? Or was one just a accidental publish?

Given that CRYSTALS-Kyber is heading towards standardization I really think there should be a good pure Rust implementation. So I want to cheer you on in this project! :partying_face:

**Comment by Zk2u** [comment]
Krystals (df8ab6bc76a2e0c77a9e735fd874ecc0f1dc96eb)

**Comment by faern** [comment]
Cool. Unfortunate that the project seems quite dead.
